name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v1
    - name: Execute a build
      run: ./gradlew check | return 0
    - run: ls -lR .
      if: always()
    - name: Upload errors
      if: always()
      uses: actions/upload-artifact@master
      with:
        name: error-report
        path: paparazzi-gradle-plugin/build/reports/tests/test/index.html
